language: node_js

node_js:
  - 11
  - 10

# Retry install on fail to avoid failing a build on network/disk/external errors
install:
  - travis_retry npm install

script:
  - npm test

jobs:
  include:
    - stage: release
      node_js: lts/*
      script:
        - npm run release
